config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "http://0.0.0.0:3000/"

  devise_for :users
  root to: 'pages#home'

  resources :admin_pannel, only: [:index]
  get "admin_pannel/groups", to: "admin_pannel#group", as: :admin_pannel_groups

  # devise_for :users, controllers: { invitations: 'users/invitations' }

  # get "groups/:group_id/memberships", to: "memberships#index", as: :memberships
  # resources :memberships, controllers: {invitations: 'memberships/invitations'}
  # resources :memberships, only: [:index]
#
# devise_for :users_admin

  resources :groups do
    # resources :invites, only: [:new, :create, :index]
    # resources :invites
    # , only: [:new, :create]
    # get "groups/:group_id/invites", to: "invites#new", as: :invite
    resources :memberships, only: [:new, :create, :index, :edit, :destroy]
    patch "groups/:group_id/dinners/:dinner_id/memberships/:memberships_id", to: "memberships#update", as: :dinner_membership
    resources :dinners, only: [:new, :create, :edit, :update, :destroy, :show]

    resources :dinners do
      resources :attendees, only: [:create, :show, :update]
    end
  end
end

app/controllers/admin_pannel_controller.rb
class AdminPannelController < ApplicationController
  before_action :check_if_admin

  def index
    # Zoekfunctie voor Users
    @search = params[:search]
    if @search.present?
      @query = @search[:query]
      if @query.empty?
        @user = User.all
      else
        @user = User.where("last_name ILIKE ?", @query)
      end
    else
      @user = User.all
    end

  end

  def group
    # filter voor groupen
    @query = params[:filter]
    if @query.present?
      @field = @query[:field]
      if @field.empty?
        @dinners = Dinner.all
      else
        @dinners = Dinner.where(id: @field)
      end
    else
      @dinners = Dinner.all
    end
  end

  private

  def check_if_admin
    redirect_to root_path unless current_user.admin?
  end

  def search_params
    params.require(:search).permit(:query)
  end

  def filter_params
    params.require(:filter).permit(:field)
  end

end

app/helpers/admin_pannel_helper.rb
module AdminPannelHelper
end

app/views/admin_pannel/group.html.erb
<div class="container">

  <%= simple_form_for :filter, url: admin_pannel_groups_path, method: "GET" do |f| -%>
  <%= f.input :field, collection: Dinner.all, include_blank: false, prompt: "Filter" %>
  <%= f.submit "Filter", class: "btn btn-primary" %>
  <% end -%>

  <% @dinners.each do |dinner| %>
    <h1><%= Group.find(dinner.group_id).name %></h1>
    <h3><%= dinner.name %></h3>
<!--    complex eager Loading => GROUP_BY-->
    <h4>Total ammount of attendees: <%= Attendee.joins(:membership).group(:dinner_id).where(dinner_id: dinner.id).count[dinner.id] %></h4>

    <hr style="border-top: 1px solid #ccc;">

    <table class="table">
      <thead>
      <h4 class="text-center">Attendees per group</h4>
      <tr>
        <th scope="col">user ID</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
      </tr>
      </thead>
      <tbody>
      <% @attendees = Attendee.joins(:membership).where(dinner_id: dinner.id) %>
      <% @attendees.each do |attendee| %>
        <% @user = User.find(Membership.find(attendee.membership_id).user_id) %>
        <tr>
          <th scope="row"><%= @user.id %></th>
          <td><%= @user.first_name %></td>
          <td><%= @user.last_name %></td>
          <td><%= @user.email %></td>
        </tr>
      <% end %>

      </tbody>
    </table>
    <hr style="border-top: 2px solid black;">

<% end %>

</div>

app/views/admin_pannel/index.html.erb
<br>
<h1 class="text-center">Admin pannel</h1>

<div class="container">
  <br>

  <%= link_to "go to groups", admin_pannel_groups_path %>

  <%= simple_form_for :search, url: admin_pannel_index_path, method: "GET", html: {class: 'form-inline'} do |f| %>
    <%= f.input :query, input_html: {value: "", title: "Search"}, placeholder: "Only last name" %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>

  <br>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">User Name</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Admin</th>
      <th scope="col">User Created</th>
      <th scope="col">User Modified</th>

    </tr>
    </thead>
    <tbody>
    <% @user.each do |user| %>
      <tr>
        <!-- <th scope="row">
        <% user.id %></th> -->
        <td><%= user.user_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.created_at.strftime("%a %e %b %Y / %T ") %></td>
        <td><%= user.updated_at.strftime("%a %e %b %Y / %T ") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>