config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "http://0.0.0.0:3000/"

  devise_for :users
  root to: 'pages#home'

  resources :admin_pannel, only: [:index]
  get "admin_pannel/groups", to: "admin_pannel#group", as: :admin_pannel_groups

  # devise_for :users, controllers: { invitations: 'users/invitations' }

  # get "groups/:group_id/memberships", to: "memberships#index", as: :memberships
  # resources :memberships, controllers: {invitations: 'memberships/invitations'}
  # resources :memberships, only: [:index]
#
# devise_for :users_admin

  resources :groups do
    # resources :invites, only: [:new, :create, :index]
    # resources :invites
    # , only: [:new, :create]
    # get "groups/:group_id/invites", to: "invites#new", as: :invite
    resources :memberships, only: [:new, :create, :index, :edit, :destroy]
    patch "groups/:group_id/dinners/:dinner_id/memberships/:memberships_id", to: "memberships#update", as: :dinner_membership
    resources :dinners, only: [:new, :create, :edit, :update, :destroy, :show]

    resources :dinners do
      resources :attendees, only: [:create, :show, :update]
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  # through: :memberships

  has_many :dinners, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :group_show, only: %i[show]
  def index
    groups_registered = Group.joins(:memberships).where(memberships: { user_id: current_user.id})
    @groups = policy_scope(groups_registered).order(created_at: :desc)
  end

  # if admin and he is owner of the group then show hin the admin details

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    authorize @group
    if @group.save
      Membership.create(user_id: current_user.id, group_id: @group.id, email: current_user.email)
      redirect_to groups_path, notice: "Group #{@group.name} was succesfully created!"
    else
      render :new
    end
  end

  def edit; end

  def new
    @group = Group.new
    authorize @group
  end

  def update
  end

  def show
    @members = Membership.where(group_id: @group.id)
    @member = Membership.where(user_id: current_user).where(group_id: @group.id).first
    @dinners = Dinner.where(group_id: @group.id)
  end

  def destroy
  end

  private

  def group_show
    @group = Group.find(params[:id])
    authorize @group
  end

  def group_params
    params.require(:group).permit(:name, :user_id)
  end
end

app/views/groups/destroy.html.erb
<h1>Group#destroy</h1>
<p>Find me in app/views/group/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1>Group#edit</h1>
<%= form_for @invite , :url => invites_path do |f| %>
  <%= f.hidden_field :group_id, :value => @invite.group_id %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit 'Send' %>
<% end %>

app/views/groups/index.html.erb
<hr>
<h1 class="text-center">All Groups</h1>
<hr>


<div class="container">
  <%= link_to "new Group", new_group_path, class: "btn btn-primary w-100 mb-4"  %>

  <% @groups.each do |group| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= link_to group.name.capitalize, group_path(group), style: "color:white" %>
    </div>
    <br>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>Create new Group</h1>

<%= simple_form_for @group do |f| -%>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?  %>
  <%= f.input :name  %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end -%>

app/views/groups/show.html.erb
<div class="container">
  <hr>
  <h1 class="text-center"><%= @group.name.capitalize %></h1>
  <hr>
  <div class="admin_pannel">
    <h3>Admin pannel</h3>
      <%= link_to "Back to groups", groups_path  %> |
      <%= link_to "Organize Dinner", new_group_dinner_path(@group)  %> |
      <%= link_to "Invite People to the group", new_group_membership_path(@group) %>
  </div>
  <div class="members">
    <h3>Group members</h3>
    <div class="row justify-content-around">
      <% @members.each do |member| %>
        <div class="col-lx-6">
          <div class="card-member">
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg">
            <div class="card-member-infos">
              <h2><%= member.user.first_name %> <%= member.user.last_name %></h2>
              <% if @group.user_id == current_user.id %>
              <%= link_to "delete", group_membership_path(@group, member), class: "btn btn-danger mt-2", data: {confirm: "Are you shure you want to #{member.user.first_name} #{member.user.last_name} this member from the group"}, method: :delete  %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
  </div>

  <div class="dinners">
    <h3>Dinners</h3>
    <div class="row d-flex align-items-center justify-content-around">
      <% @dinners.each do |dinner| %>
          <div class="card-dinner col-md-5">
            <div class="card-dinner-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
              <%= link_to dinner.name, group_dinner_path(@group, dinner) %>
            </div>
              <div class="card-dinner-body">
                Here some text
              </div>
              <% if current_user.admin %>
              <div class="card-dinner-footer">
                <%= link_to (raw('<span class="icon text-white-50"><i class="far fa-edit"></i></span><span class="text">Edit</span>')), edit_group_dinner_path(@group, dinner), class: "btn btn-primary btn-icon-split" %>
                <%= link_to (raw('<span class="icon text-white-50"><i class="far fa-trash-alt"></i></span><span class="text">Delete</span>')), group_dinner_path(@group, dinner), class: "btn btn-danger btn-icon-split" , data: {confirm: "Are you sure you whant to delete #{dinner.name}?"}, method: :delete %>
              </div>
              <% end %>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/groups/update.html.erb
<h1>Group#update</h1>
<p>Find me in app/views/group/update.html.erb</p>