config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "http://0.0.0.0:3000/"

  devise_for :users
  root to: 'pages#home'

  resources :admin_pannel, only: [:index]
  get "admin_pannel/groups", to: "admin_pannel#group", as: :admin_pannel_groups

  # devise_for :users, controllers: { invitations: 'users/invitations' }

  # get "groups/:group_id/memberships", to: "memberships#index", as: :memberships
  # resources :memberships, controllers: {invitations: 'memberships/invitations'}
  # resources :memberships, only: [:index]
#
# devise_for :users_admin

  resources :groups do
    # resources :invites, only: [:new, :create, :index]
    # resources :invites
    # , only: [:new, :create]
    # get "groups/:group_id/invites", to: "invites#new", as: :invite
    resources :memberships, only: [:new, :create, :index, :edit, :destroy]
    patch "groups/:group_id/dinners/:dinner_id/memberships/:memberships_id", to: "memberships#update", as: :dinner_membership
    resources :dinners, only: [:new, :create, :edit, :update, :destroy, :show]

    resources :dinners do
      resources :attendees, only: [:create, :show, :update]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/608/608857.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Groups", groups_path , class: "nav-link" %>
        </li>
        <% full_user_name = "#{current_user.first_name} #{current_user.last_name}" %>
        <li class="nav-item"> <%= link_to full_user_name, edit_user_registration_path, class: "nav-link"  %></li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.user_photo, crop: :thumb, radius: :max, height: 50, width: 50, gravity: :face , class: " dropdown-toggle img-profile rounded-circle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
     <!--      < image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false > -->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create Group", new_group_path, class: "dropdown-item" %>
            <%= link_to "add Members", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>