config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "http://0.0.0.0:3000/"

  devise_for :users
  root to: 'pages#home'

  resources :admin_pannel, only: [:index]
  get "admin_pannel/groups", to: "admin_pannel#group", as: :admin_pannel_groups

  # devise_for :users, controllers: { invitations: 'users/invitations' }

  # get "groups/:group_id/memberships", to: "memberships#index", as: :memberships
  # resources :memberships, controllers: {invitations: 'memberships/invitations'}
  # resources :memberships, only: [:index]
#
# devise_for :users_admin

  resources :groups do
    # resources :invites, only: [:new, :create, :index]
    # resources :invites
    # , only: [:new, :create]
    # get "groups/:group_id/invites", to: "invites#new", as: :invite
    resources :memberships, only: [:new, :create, :index, :edit, :destroy]
    patch "groups/:group_id/dinners/:dinner_id/memberships/:memberships_id", to: "memberships#update", as: :dinner_membership
    resources :dinners, only: [:new, :create, :edit, :update, :destroy, :show]

    resources :dinners do
      resources :attendees, only: [:create, :show, :update]
    end
  end
end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :group
  has_many :attendees, dependent: :destroy
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  before_action :group_show, only: %i[new create show destroy update edit]
  before_action :dinner_show, only: %i[show edit update destroy]

  def index
    @dinners = policy_scope(Dinner).order(created_at: :desc)
  end

  def new
    @dinner = Dinner.new
    authorize @dinner
  end

  def create
    @dinner = Dinner.new(dinner_params)
    @dinner.group_id = group_show.id
    @dinner.organizer_id = current_user.id
    authorize @dinner
    if @dinner.save

      current_member = Membership.where(user_id: current_user).where(group_id: @dinner.group_id).first
      # current_member.attending = true

      group_members = Membership.where(group_id: group_show)
      group_members.each do |member|
        Attendee.create!(dinner_id: @dinner.id, membership_id: member.id)
      end
      organizer = Attendee.where(membership_id: current_member).first
      organizer.attending = true
      organizer.save

      redirect_to group_dinner_path(group_show, @dinner), notice: "Dinner #{@dinner.name} was succesfully created"

    else
      render :new
    end
  end

  def show
    @organizer = User.where(id: @group.user_id).first
    @member = Membership.where(user_id: current_user).where(group_id: @group.id).first
    @attendee = Attendee.where(membership_id: @member.id).where(dinner_id: @dinner.id).first
    @attendees = Attendee.joins(:membership).where(dinner_id: @dinner.id).where(memberships: { group_id: @group.id })
  end

  def destroy
    @dinner.destroy
    redirect_to group_path(@group)
  end

  def edit; end

  def update
    if @dinner.update(dinner_params)
      redirect_to group_dinner_path(@group, @dinner)
    else
      render :edit
    end
  end

  private

  def dinner_show
    @dinner = Dinner.find(params[:id])
    authorize @dinner
  end

  def group_show
    @group = Group.find(params[:group_id])
    authorize @group
  end

  def dinner_params
    params.require(:dinner).permit(:name, :datetime, :group_id)
  end

end

app/views/dinners/_form.html.erb
<%= simple_form_for [@group, @dinner] do |f| -%>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?  %>
  <%= f.input :name, placeholder: "name of the dinner", input_html: { autocomplete: "name" } %>
  <%= f.input :datetime, order: [:day, :month, :year ], input_html: { autocomplete: "datetime" } %>
  <%= f.button :submit, class: "btn btn-primary"  %>
<% end -%>

app/views/dinners/edit.html.erb
<hr>
<h1 class="text-center"><%= @dinner.name %></h1>
<hr>
<%= render 'form' %>

<br>

<h4>Date:<%= @dinner.date %></h4>

app/views/dinners/index.html.erb
<hr>
<h1 class="text-center">Dinners</h1>
<hr>
<div class="container">
<% @dinners.each do |dinner| %>
  <div class="card-product">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg">
    <div class="card-product-infos">
      <h2><%= dinner.name %></h2>
      <p><%= dinner.date.strip %></p>
    </div>
  </div>


<% end %>
<br>
<hr>
<%= link_to "Orgenize new Dinner", new_dinner_path  %>
</div>

app/views/dinners/new.html.erb
<h1>New Dinner</h1>

<div class="container">
<%= render 'form' %>
</div>

app/views/dinners/show.html.erb
<hr>
<h1 class="text-center"><%= @dinner.name %></h1>
<hr>

<div class="container">
  <br>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%= current_user.first_name %> <%= current_user.last_name %></h6>
    </div>
    <div class="your-status container">
      <%= render 'attendees/form' %>
    </div>
  </div>
  <!--   Display table in partial -->
  <!--
  <% render 'attendees/status' %> -->

  <table class="table table-dark">
    <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Attending</th>
      <th scope="col">Guests</th>
      <th scope="col">Comment</th>
      <th scope="col">Email</th>
      <% if current_user == @organizer %>
        <th scope="col">Change Attending</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <tr>
      <% @attendees.each do |attendant| %>
      <tr>
        <td><%= attendant.membership.user.first_name %></td>
        <td><%= attendant.membership.user.last_name %></td>
        <td><%= attendant.attending %></td>
        <td><%= attendant.guests %></td>
        <td><%= attendant.comment %></td>
        <td><%= attendant.membership.email %></td>
        <% if current_user == @organizer %>
          <td>
            <%= simple_form_for [@group, @dinner, @attendee] do |f| -%>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <%= f.input :attendant_id, as: :hidden, input_html: {value: attendant.id, style: "display: none"} %>
              <%= f.button :submit, class: "btn btn-primary" %>
            <% end -%>
          </td>
        <% end %>


      </tr>
    <% end %>
    </tr>
    </tbody>
  </table>
  <%= link_to "back", group_path(@group), class: "btn btn-primary" %>
</div>